# Generated by Django 3.2.5 on 2021-07-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='alert_status',
            field=models.CharField(choices=[('danger', 'Danger'), ('success', 'Success'), ('info', 'Info'), ('warning', 'Warning')], default='info', max_length=10),
        ),
    ]
